### ISSUE TITLE
Unable to build this project.

### ISSUE THREAD

**Issue by nomstradamus** [spring-cloud-samples/configserver#6]
I am unable to build this project as the POM refers to parent pom which does not exist. Can we have one which build and runs.

**Comment by spencergibb** [comment]
Could you provide errors or maven output?  The pom exists in the repo.spring.io snapshots repo.  maybe you have a maven cache problem?

**Comment by dsyer** [comment]
Maybe this wasn't building cleanly at first when we switched over to 1.0.1.BUILD-SNAPSHOT? Should be OK now.

**Comment by wstrater** [comment]
I am still experiencing issues with building the project. The issue may be user related because I am new to Spring Boot, Cloud and Maven but looking to adopt the first two. 

I was trying to follow the Quick Start on http://projects.spring.io/spring-cloud/ but was not sure how to get from a 3 line code snippet to a running server so I tried one so the samples on the side.

$ mkdir samples
$ cd samples
$ git clone https://github.com/spring-cloud-samples/configserver.git
Cloning into 'configserver'...
remote: Counting objects: 375, done.
remote: Total 375 (delta 0), reused 0 (delta 0), pack-reused 375
Receiving objects: 100% (375/375), 48.25 KiB, done.
Resolving deltas: 100% (149/149), done.

$ cd configserver/
$ mvn spring-boot:run
[INFO] Scanning for projects...
Downloading: http://bri-107106/archiva/repository/internal/org/springframework/cloud/spring-cloud-starter-parent/1.0.1.BUILD-SNAPSHOT/maven-metadata.xml
Downloading: http://bri-107106/archiva/repository/internal/org/springframework/cloud/spring-cloud-starter-parent/1.0.1.BUILD-SNAPSHOT/spring-cloud-starter-parent-1.0.1.BUILD-SNAPSHOT.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.demo:configserver:0.0.1-SNAPSHOT (/usr/local/spring-1.3.0.BUILD-SNAPSHOT/samples/configserver/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.springframework.cloud:spring-cloud-starter-parent:pom:1.0.1.BUILD-SNAPSHOT in archiva.internal (http://bri-107106/archiva/repository/internal/) and 'parent.relativePath' points at no local POM @ line 14, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by spencergibb** [comment]
@wstrater looks like you have an internal repository you are being forced to: `http://bri-107106/archiva/repository/internal/`.

**Comment by wstrater** [comment]
I helped some one with a POC a while ago and he had me use a local Maven repository. Never worked for me so I forgot about it because we build with Ant. I guess it must be configured in my home directory. Sorry for the confusion.

Wes.
